server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/esa_database
spring.datasource.username=sobusdas
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ignore extra fields in json so old and new pages keep working
spring.jackson.deserialization.fail-on-unknown-properties=false
